version: "2"
services:
  sut:
    image: appcelerator/sut
    build:
      context: ./sut
      dockerfile: Dockerfile

  telegraf:
    image: appcelerator/telegraf:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    environment:
      OUTPUT_INFLUXDB_ENABLED: "true"
      INFLUXDB_URL: "http://influxdb:8086"
      INPUT_DOCKER_ENABLED: "true"
    labels:
      - "ServiceUUId=system.telegraf"
      - "io.appcelerator.amp.build.mounts=/var/run/docker.sock,/var/run/utmp"

  influxdb:
    image: appcelerator/influxdb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      FORCE_HOSTNAME: auto
      CONFIG_ARCHIVE_URL: "https://github.com/appcelerator/amp-config/archive/0.2.0.tar.gz"
      PRE_CREATE_DB: "telegraf"
