version: '2'
services:
  consul:
    extends:
      file: docker-compose.yml
      service: consul
  telegraf:
    extends:
      file: docker-compose.yml
      service: telegraf
    environment:
      INTERVAL: 3s
      FLUSH_INTERVAL: 3s
      FLUSH_JITTER: 0.2s
    depends_on:
      - consul
      - influxdb
  influxdb:
    extends:
      file: docker-compose.yml
      service: influxdb
    depends_on:
      - consul
  sut:
    image: appcelerator/sut
    build: ./sut
    depends_on:
      - telegraf
      - influxdb
