version: '2'
services:
  telegraf:
    extends:
      file: docker-compose.yml
      service: telegraf
    depends_on:
      - influxdb
  influxdb:
    extends:
      file: docker-compose.yml
      service: influxdb
