version: '2'
services:
  consul:
    container_name: consul
    extends:
      file: docker-compose.yml
      service: consul
  telegraf:
    container_name: telegraf
    extends:
      file: docker-compose.yml
      service: telegraf
    depends_on:
      - consul
      - influxdb
  influxdb:
    container_name: influxdb
    extends:
      file: docker-compose.yml
      service: influxdb
    depends_on:
      - consul
  sut:
    extends:
      file: docker-compose.yml
      service: sut
    depends_on:
      - telegraf
      - influxdb
